-- CyFAST cross-platform execution lifecycle
-- Additive and repeat-safe. Existing Windows W1, orchestration, generation, and audit tables are preserved.

CREATE TABLE IF NOT EXISTS execution_target (
  execution_target_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  platform VARCHAR(32) NOT NULL,
  endpoint VARCHAR(2048) NOT NULL,
  credential_reference VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
  capabilities JSON NOT NULL,
  configuration JSON NOT NULL,
  last_seen_at DATETIME(3) NULL,
  last_health JSON NULL,
  revoked_at DATETIME(3) NULL,
  version INT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_target_id),
  KEY ix_execution_target_scope (organization_id, project_id, platform, status),
  KEY ix_execution_target_last_seen (organization_id, last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_run (
  execution_run_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_target_id VARCHAR(64) NOT NULL,
  test_script_id VARCHAR(64) NOT NULL,
  test_script_version VARCHAR(64) NULL,
  parent_execution_run_id VARCHAR(64) NULL,
  root_execution_run_id VARCHAR(64) NULL,
  attempt_number INT NOT NULL DEFAULT 1,
  platform VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  correlation_id VARCHAR(64) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  requested_by VARCHAR(100) NOT NULL,
  external_execution_id VARCHAR(128) NULL,
  package_sha256 VARCHAR(64) NULL,
  package_manifest JSON NULL,
  runtime_snapshot JSON NULL,
  result_summary JSON NULL,
  real_execution TINYINT(1) NOT NULL DEFAULT 0,
  simulated TINYINT(1) NOT NULL DEFAULT 0,
  target_connected TINYINT(1) NOT NULL DEFAULT 0,
  session_created TINYINT(1) NOT NULL DEFAULT 0,
  meaningful_actions INT NOT NULL DEFAULT 0,
  meaningful_assertions INT NOT NULL DEFAULT 0,
  exit_code INT NULL,
  failure_classification VARCHAR(64) NULL,
  failure_message TEXT NULL,
  proof_hash VARCHAR(64) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_run_id),
  UNIQUE KEY ux_execution_run_idempotency (organization_id, idempotency_key),
  KEY ix_execution_run_scope_status (organization_id, project_id, status, created_date),
  KEY ix_execution_run_root_attempt (root_execution_run_id, attempt_number),
  KEY ix_execution_run_target_status (execution_target_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_event (
  execution_event_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_run_id VARCHAR(64) NOT NULL,
  sequence_number BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(100) NULL,
  payload JSON NOT NULL,
  payload_hash VARCHAR(64) NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_event_id),
  UNIQUE KEY ux_execution_event_sequence (execution_run_id, sequence_number),
  KEY ix_execution_event_scope_type (organization_id, project_id, event_type, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_artifact (
  execution_artifact_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_run_id VARCHAR(64) NOT NULL,
  artifact_type VARCHAR(64) NOT NULL,
  storage_file_id VARCHAR(128) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(255) NOT NULL,
  content_hash VARCHAR(64) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  retention_classification VARCHAR(64) NOT NULL DEFAULT 'STANDARD',
  metadata JSON NULL,
  captured_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_artifact_id),
  UNIQUE KEY ux_execution_artifact_content (execution_run_id, artifact_type, content_hash),
  KEY ix_execution_artifact_scope_type (organization_id, project_id, artifact_type, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_recording (
  execution_recording_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_run_id VARCHAR(64) NOT NULL,
  execution_artifact_id VARCHAR(64) NOT NULL,
  recording_type VARCHAR(32) NOT NULL,
  format VARCHAR(32) NOT NULL,
  redacted TINYINT(1) NOT NULL DEFAULT 1,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NOT NULL,
  metadata JSON NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_recording_id),
  KEY ix_execution_recording_run_time (execution_run_id, started_at),
  KEY ix_execution_recording_scope_type (organization_id, project_id, recording_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_defect (
  execution_defect_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_run_id VARCHAR(64) NOT NULL,
  root_execution_run_id VARCHAR(64) NOT NULL,
  rerun_execution_run_id VARCHAR(64) NULL,
  requirement_id VARCHAR(64) NULL,
  test_scenario_id VARCHAR(64) NULL,
  test_case_id VARCHAR(64) NULL,
  test_script_id VARCHAR(64) NULL,
  classification VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  title VARCHAR(512) NOT NULL,
  description TEXT NULL,
  expected_result TEXT NULL,
  actual_result TEXT NULL,
  assigned_to VARCHAR(100) NULL,
  product_repository VARCHAR(512) NULL,
  product_commit VARCHAR(128) NULL,
  product_pull_request VARCHAR(512) NULL,
  resolution TEXT NULL,
  resolved_at DATETIME(3) NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_defect_id),
  KEY ix_execution_defect_scope_status (organization_id, project_id, status, severity),
  KEY ix_execution_defect_root_class (root_execution_run_id, classification)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS execution_repair_attempt (
  execution_repair_attempt_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_run_id VARCHAR(64) NOT NULL,
  rerun_execution_run_id VARCHAR(64) NULL,
  attempt_number INT NOT NULL,
  failure_classification VARCHAR(64) NOT NULL,
  base_script_version VARCHAR(64) NULL,
  proposed_script_hash VARCHAR(64) NOT NULL,
  proposed_patch LONGTEXT NOT NULL,
  rationale TEXT NULL,
  validation_result JSON NULL,
  approval_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  approved_by VARCHAR(100) NULL,
  approved_at DATETIME(3) NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_repair_attempt_id),
  UNIQUE KEY ux_execution_repair_attempt (execution_run_id, attempt_number),
  KEY ix_execution_repair_scope_approval (organization_id, project_id, approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
