CREATE TABLE IF NOT EXISTS quality_lifecycle_content (
  quality_lifecycle_content_id VARCHAR(64) NOT NULL,
  quality_lifecycle_id VARCHAR(64) NOT NULL,
  quality_lifecycle_item_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  item_type VARCHAR(64) NOT NULL,
  resource_id VARCHAR(128) NOT NULL,
  resource_version VARCHAR(128) NOT NULL,
  title VARCHAR(512) NOT NULL,
  content_format VARCHAR(32) NOT NULL,
  content_text LONGTEXT NULL,
  content_json JSON NULL,
  content_hash VARCHAR(64) NOT NULL,
  source_hash VARCHAR(64) NOT NULL,
  schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  model_id VARCHAR(255) NULL,
  prompt_version VARCHAR(128) NULL,
  generation_status VARCHAR(32) NOT NULL DEFAULT 'GENERATED',
  validation_result JSON NOT NULL,
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (quality_lifecycle_content_id),
  UNIQUE KEY ux_quality_lifecycle_content_item (quality_lifecycle_item_id),
  UNIQUE KEY ux_quality_lifecycle_content_version
    (quality_lifecycle_id, item_type, resource_id, resource_version),
  KEY ix_quality_lifecycle_content_scope
    (organization_id, project_id, item_type, generation_status),
  KEY ix_quality_lifecycle_content_hash (content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
