CREATE TABLE IF NOT EXISTS execution_product_fix (
  execution_product_fix_id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  project_id INT NOT NULL,
  execution_defect_id VARCHAR(64) NOT NULL,
  source_execution_run_id VARCHAR(64) NOT NULL,
  root_execution_run_id VARCHAR(64) NOT NULL,
  repository_url VARCHAR(2048) NOT NULL,
  base_branch VARCHAR(255) NOT NULL,
  fix_branch VARCHAR(255) NOT NULL,
  pull_request_url VARCHAR(2048) NULL,
  commit_sha VARCHAR(64) NULL,
  change_summary LONGTEXT NOT NULL,
  risk_assessment JSON NOT NULL,
  review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  reviewed_by VARCHAR(100) NULL,
  reviewed_at DATETIME(3) NULL,
  deployment_environment VARCHAR(255) NULL,
  deployment_id VARCHAR(255) NULL,
  deployment_version VARCHAR(255) NULL,
  deployment_status VARCHAR(32) NOT NULL DEFAULT 'NOT_DEPLOYED',
  deployed_at DATETIME(3) NULL,
  verification_execution_run_id VARCHAR(64) NULL,
  verification_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
  created_by VARCHAR(100) NULL,
  created_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  modified_by VARCHAR(100) NULL,
  modified_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_by VARCHAR(100) NULL,
  deleted_date DATETIME(3) NULL,
  PRIMARY KEY (execution_product_fix_id),
  UNIQUE KEY ux_execution_product_fix_branch (execution_defect_id, fix_branch),
  KEY ix_execution_product_fix_scope
    (organization_id, project_id, review_status, deployment_status),
  KEY ix_execution_product_fix_root (root_execution_run_id, created_date),
  KEY ix_execution_product_fix_verification (verification_execution_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
